# COURSE: A deep understanding of deep learning
## SECTION: Introduction to Python: functions
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202212
##### Modified from original code

# .
# .
# .

# VIDEO: Inputs and outputs

In [1]:
# Behind the scene, python adds all the elements together in the collection
sum([10,20,30,40.5])

100.5

In [11]:
# What crashes the program
sum(["a","b","c"]) 
sum([1, 2, 3, "4"])

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [13]:
alist = [2,3,4]

sum(alist)

9

In [ ]:
# alist(0)
sum[alist]

In [ ]:
len(alist)

In [14]:
# function gives outputs
listsum = sum(alist)
print('The sum is ' + str(listsum))

The sum is 9


### Exercise

In [15]:
# compute the average of alist
sum(alist) / len(alist)

3.0

# .
# .
# .

# VIDEO: Python modules (numpy, pandas)


In [1]:
# Not gonna work
numbers = [1,2,3,4,5]
mean(numbers)
average(numbers)

NameError: name 'mean' is not defined

In [17]:
# Libraries keep python lightweighted
# Numerical Python (numpy)
import numpy as np
# from numpy import mean as m ##if you only need 1 function

In [ ]:
# Find the mean of the collection
np.mean(numbers)

In [5]:
# Find the array of linearly spaced numbers from 1 to 5
# There will be 7 of them
np.linspace(1,5,7)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [14]:
# new data type: numpy array
numbernp = np.array([1,2,3,4,5])
numbers = numbernp.tolist()

print(numbernp)
print(numbers)

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [8]:
print(type(numbernp))
print(type(numbers))

<class 'numpy.ndarray'>
<class 'list'>


In [10]:
# Find min and max of the numpy array
print(numbernp.min())
print(numbernp.max())

1
5


In [ ]:
n = [4,3,5,2,6,1,7]
print(n)
print(n)

In [16]:
n = [4,3,5,2,6,1,7]
print(n)
n = np.sort(n) # notice different variable type; could set back
print(n)

[4, 3, 5, 2, 6, 1, 7]
[1 2 3 4 5 6 7]


In [19]:
# in-place vs out-of-place
n = [4,3,5,2,6,1,7]
nn = np.array(n)
n.sort() #inplace: changes the original variable 
print(n)
np.sort(nn) #out-of-place: returns a new copy of the original variable
print(nn)

[1, 2, 3, 4, 5, 6, 7]
[4 3 5 2 6 1 7]


In [35]:
# Pandas Library
# organizes dataset by observations vs. features
import pandas as pd

# create some random data
var1 = np.random.randn() #create a random # from Gaussian distribution
var2 = np.random.randn(5) #create an array of 5 random numbers
var3 = np.random.randn(5,5) #create a 5x5 matrix of random numbers

print(var1)
print(var2)
print(var3)

0.2654170938372633
[ 1.78055481 -0.08887007  0.23523495 -0.25961866 -0.20790204]
[[ 0.10498593 -1.93354312 -0.23553651 -0.31402295  1.73140844]
 [ 1.50261226 -0.41164231  1.0478197  -0.53208973 -0.70143619]
 [ 0.15016968 -0.06915175  0.77768974  0.50432974  0.78273612]
 [-1.48490164 -0.91615472 -0.68649677 -0.808455   -0.61804403]
 [ 0.23360053  1.50202589  0.34481741  0.53273729  0.90925258]]


In [76]:
# create some random data II
var1 = np.random.randn(100) *5 + 20
var2 = np.random.randn(100) > 0

# variable labels (headers)
labels = ['Temp. (C)','Ice cream']

# put them into a dictionary
D = {labels[0]:var1, labels[1]:var2}

# import to pandas dataframe
df = pd.DataFrame(data=D)

In [77]:
df

Temp. (C)  Ice cream
0   12.387891      False
1   20.543456      False
2   19.455437      False
3   16.832326      False
4   14.747855       True
..        ...        ...
95  19.294328       True
96  22.395569      False
97  21.144991      False
98  19.801850      False
99  13.308550       True

[100 rows x 2 columns]

In [ ]:
df.head()

In [79]:
# Return how many observations (rows) we have for each column
df.count()

Temp. (C)    100
Ice cream    100
dtype: int64

In [81]:
# Return the mean of values for each column
df.mean()

Temp. (C)    19.432548
Ice cream     0.540000
dtype: float64

### Exercise

In [83]:
# create a pandas dataframe with variables: 
# integers from 0 to 10, their square, and their log

nums = np.array(range(11))
# Here throws a warning of divison by 0
# Warning: Python thinks u did smth wrong
# Error: You definitely did smth wrong
dictionary = { 'num': nums, 'square': nums**2, 'log': np.log(nums) }
finaldf = pd.DataFrame(data=dictionary)
finaldf

/var/folders/3k/vsl4hddn56x_g6r3lg43yr8r0000gn/T/ipykernel_1794/2580614614.py:5: RuntimeWarning: divide by zero encountered in log
  dictionary = { 'num': nums, 'square': nums**2, 'log': np.log(nums) }


num  square       log
0     0       0      -inf
1     1       1  0.000000
2     2       4  0.693147
3     3       9  1.098612
4     4      16  1.386294
5     5      25  1.609438
6     6      36  1.791759
7     7      49  1.945910
8     8      64  2.079442
9     9      81  2.197225
10   10     100  2.302585

# .
# .
# .

# VIDEO: Getting help on functions

In [ ]:
# Help!
# Click on the parenthesis inside the function -> Hit shift/tab at the same time
# This gives you documentation of the function
alist = [1,2,3]

sum(alist,10)

In [90]:
# You can also do this
sum??

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method

In [91]:
# You can also do this
# But this prints the plain text of the documentation
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [93]:
# advanced method

import inspect
import numpy as np
inspect.getsourcelines(np.linspace)

(['@array_function_dispatch(_linspace_dispatcher)\n',
  'def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,\n',
  '             axis=0):\n',
  '    """\n',
  '    Return evenly spaced numbers over a specified interval.\n',
  '\n',
  '    Returns `num` evenly spaced samples, calculated over the\n',
  '    interval [`start`, `stop`].\n',
  '\n',
  '    The endpoint of the interval can optionally be excluded.\n',
  '\n',
  '    .. versionchanged:: 1.16.0\n',
  '        Non-scalar `start` and `stop` are now supported.\n',
  '\n',
  '    .. versionchanged:: 1.20.0\n',
  '        Values are rounded towards ``-inf`` instead of ``0`` when an\n',
  '        integer ``dtype`` is specified. The old behavior can\n',
  '        still be obtained with ``np.linspace(start, stop, num).astype(int)``\n',
  '\n',
  '    Parameters\n',
  '    ----------\n',
  '    start : array_like\n',
  '        The starting value of the sequence.\n',
  '    stop : array_like\n',
  '        The 

# . 
# . 
# . 

# VIDEO: Creating functions

In [3]:
def awesomeFunction():
  print(1+1)

In [5]:
awesomeFunction #function instance
awesomeFunction() #call function

2


In [8]:
# Functions with comma-separated parameters
# Also return values
def SuperAwesomeFunction(input1,input2):
  return input1 + input2

In [11]:
SuperAwesomeFunction(5,8)

13

In [9]:
answer = SuperAwesomeFunction(5,8)


In [10]:
print(answer)

13


In [13]:
# with multiple outputs
def awesomeFunction(in1,in2):
  sumres = in1+in2
  prodres = in1*in2
  print('Their sum is ' + str(sumres))
  print('Their product is ' + str(prodres))
  return sumres,prodres

In [14]:
out1,out2 = awesomeFunction(4,5)

print(out1,out2)

Their sum is 9
Their product is 20
9 20


In [17]:
# lambda functions

fun = lambda x,y : x**2 + y - 1 # lambda params : value to return (operations)

fun(4, 5)

20

### Exercise

In [25]:
# create a function that computes a factorial, 
# then compare against the numpy factorial function
# hint: import math
import numpy as np

def myfactorial(n):
  return np.prod(np.arange(1,n+1))

myfactorial(5)

120

In [32]:
import math

x = 22 # myfactorial becomes inaccurate for x >~21 due to numerical overflow
print(np.arange(1,x+1))

print(myfactorial(x),math.factorial(x))
math.factorial??

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
-1250660718674968576 1124000727777607680000


Signature: math.factorial(n, /)
Docstring:
Find n!.

Raise a ValueError if x is negative or non-integral.
Type:      builtin_function_or_method

# .
# .
# .

# VIDEO: Global and local variable scopes




In [ ]:
# clear the workspace (restart the kernel)

In [1]:
def funfun():
  x = 7
  y = 10
  print(x)


In [2]:
funfun()

7


In [4]:
x

NameError: name 'x' is not defined

In [7]:
x = 3
print( funfun() )
print(x) #x is still 3 (python differentiates local & global scope)

7
None
3


In [8]:
def funfun():
  print(z)

In [11]:
funfun()

3


In [10]:
z = 3
funfun()

3


In [ ]:
# rules: 
#  1) variables created inside a function are local 
#     (accessible only inside the function)
#  2) variables created outside a function are global 
#    (accessible in or out of the function)

### Exercise

In [12]:
# write a function that flips a coin N times and reports the average

import numpy as np

def coinflip(N):
  propCoinFlips = np.mean( np.random.randn(N)>0 )
  print( str(N) + ' coin flips had ' + str(propCoinFlips*100) + '% heads.' )

In [14]:
coinflip(2000)

2000 coin flips had 50.3% heads.


# .
# .
# .

# Copies and Referents of Variables

In [19]:
# copies vs. referent

a = [4,3]
b = a#[:] ##without this, b becomes a referent of a
b[0] = 5

print(a)
print(b)

[5, 3]
[5, 3]


In [22]:
print(id(a))
print(id(b))

4627660544
4623480960


In [23]:
# More general solution to 
import copy

a = {'q':1, 'w':2}
b = copy.deepcopy(a)

print(id(a))
print(id(b))

4623615488
4623480576


# .
# .
# .

# VIDEO: Classes and object-oriented programming

In [24]:
# class is like a blueprint for a set of attributes and methods
# instance is an example
# class is a cookie cutter, instance is an individual cookie

class model(object):

  # constructor method
  def __init__(self, numlayers, numunits, name):
    self.layers  = numlayers
    self.units   = numunits # these are attributes
    self.name    = name
    self.weights = 10
  
  # other methods
  def howManyUnits(self):
    totalUnits = self.layers * self.units
    print(f'There are {totalUnits} units in the model.')

  def trainTheModel(self, x):
    self.weights += x
    return self.weights

  # toString method
  def __str__(self):
    return f'This is a {self.name} architecture.'


In [29]:
# create an instance and check it
ex = model(2,3,'cnn')
# ex.howManyUnits()
str(ex) #inherently calls ex.__str__()

'This is a cnn architecture.'

In [30]:
ex.trainTheModel(3)

13

In [ ]:
# Exercise: 
# create a new class so that 
# 1) the weights is a layers-by-units matrix, 
# 2) the weights are changed by multiplying by input x and summing input y

In [37]:
import numpy as np
class model2(object):

  # constructor method
  def __init__(self,numlayers,numunits,name):
    self.layers  = numlayers
    self.units   = numunits # these are attributes
    self.name    = name
    self.weights = np.random.randn(numlayers, numunits)
  
  # other methods
  def howManyUnits(self):
    totalUnits = self.layers * self.units
    print(f'There are {totalUnits} units in the model.')

  def trainTheModel(self,x,y):
    self.weights = self.weights*x + y

  def __str__(self):
    return f'This is a {self.name} architecture.'


In [40]:
ex1 = model2(2,3,'cnn')
print(ex1.weights)

[[-0.60368446  0.33326317  0.36794506]
 [-0.48747528 -1.88033756  0.45508725]]


In [53]:
# Potential problems: exploding/vanishing gradients 
ex1.trainTheModel(2,3)
ex1.weights

array([[303.7283887 , 423.6576854 , 428.09696731],
       [318.60316411, 140.31679236, 439.25116781]])