# COURSE: A deep understanding of deep learning
## SECTION: Introduction to Python: flow control
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202212
##### Modified from original code

# .
# .
# .

# VIDEO: If-else statements

In [3]:
# Pioneer on AI
# it allows computers to make their own decision based on context
# only runs if the condition is true
if True:
    print('True is true')


True is true


In [9]:
if False:
    print('False is true') # this never runs

print("outside if")

outside if


In [8]:
x = 4

if x==4:
    print('hello')

if '' or 0:
    print('Truthy values')

hello


In [16]:
#if-else
import numpy as np
randnum = np.random.randn()

if randnum>0:
    print(str(randnum) + ' is positive')
else:
    print(str(randnum) + ' is negative')


0.42234685172857717 is positive


In [ ]:
# slightly better coding

randnum = np.random.randn()

if randnum>0:
    outcome = 'positive'
else:
    outcome = 'negative'

print(str(randnum) + ' is ' + outcome)

In [17]:
# if-elif-else
caketype = 'chocolate'

if caketype=='carrot':
    print('Total yum!')
elif caketype=='chocolate':
    print('Yummier!')
elif caketype=='fruit':
    print('Healthy, I guess???')
else:
    print("OK, I'll try it.")

Yummier!


In [18]:
# one-liners
caketype = 'Carrot'

# just put the line right after if
if caketype[0]=='c': print('Probably carrot cake.')

# <line_to_run_if_true> if <condition> else <line_to_run_if_false>
print('Probably carrot cake.') if caketype[0]=='c' else print('I dunno')

I dunno


In [ ]:
# conjunctive conditionals
if 1<3 and 4==4:
    print('Both conditionals are true')
else:
    print('At least one condition is false')

### Exercise

In [ ]:
# create a dot product function
# function checks that both inputs are numpy arrays (hint: isinstance())
# function checks for same length of two input vectors
# returns dot product if pass, useful error message otherwise

In [20]:
def dotproduct(a,b):
    # check that both vectors are numpy arrays
    if not (isinstance(a,np.ndarray) and isinstance(b,np.ndarray)):
        raise Exception('Must be numpy array')

    # check that they have the same length
    if not len(a)==len(b):
        raise Exception('Must be the same length')
    
    # return the dot product
    return sum(a*b)

In [25]:
v = np.array([1,2,3,4]) # error when list
w = np.array([3,4,5,1])

print(v * w)
print(dotproduct(v,w)) #our implementation
print(np.dot(v,w)) #np built-in method for computing dot products

[ 3  8 15  4]
30
30


# .
# .
# .

# VIDEO: For loops

In [26]:
for i in range(6):
    print(i)

0
1
2
3
4
5


In [1]:
for i in range(4,11):
    print(i,i**2)

4 16
5 25
6 36
7 49
8 64
9 81
10 100


In [5]:
import numpy as np
numbers = np.linspace(3,17,5)

for i in range(len(numbers)):
    x = numbers[i]
    print('Iteration ' + str(i) + ' has a value of ' + str(x))

Iteration 0 has a value of 3.0
Iteration 1 has a value of 6.5
Iteration 2 has a value of 10.0
Iteration 3 has a value of 13.5
Iteration 4 has a value of 17.0


In [8]:
# Numbers is an Iterable: we can directly loop through its elements
for x in numbers:
    print(x)

3.0
6.5
10.0
13.5
17.0


In [12]:
#embed multiple flow-control statements
# % determines parity (odd/even) of a numbher
for n in range(18):
    
    if n%2==0:
        print(str(n) + ' is an even number.')
    else:
        print(str(n) + ' is an odd number.')
        

0 is an even number.
1 is an odd number.
2 is an even number.
3 is an odd number.
4 is an even number.
5 is an odd number.
6 is an even number.
7 is an odd number.
8 is an even number.
9 is an odd number.
10 is an even number.
11 is an odd number.
12 is an even number.
13 is an odd number.
14 is an even number.
15 is an odd number.
16 is an even number.
17 is an odd number.


In [ ]:
# soft- vs. hard-coding

iterations = 100

for i in range(iterations):
    pass

for i in range(100):
    pass


### Exercise

In [25]:
# create a function that reports the Fibonacci series for input N

def fibseq(N):
    fib = [0,1]
    for i in range(N-2):
        fib.append(sum(fib[-2:])) #summing previous 2 elements
    return fib


In [26]:
fibseq(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

# .
# .
# .

# VIDEO: While loop

In [5]:
# while = for + if
toggle = True
i = 0

while toggle:
  print(i)
  i += 1

  if i==8:
    toggle = False


0
1
2
3
4
5
6
7


In [ ]:
# Infinite Loops; plz interrupt the kernel to stop it
toggle = True
i = 0

while toggle:
  print(i)

  if i==8:
    i += 1
    toggle = False

In [31]:
# Loop with break statement
i = 0
while True:
  print(i)
  i += 1
  if i==8:
    break
  # can put more code here...

0
1
2
3
4
5
6
7


In [12]:
# Supports inequality too
i = 0
while i<8:
  print(i)
  i += 1

0
1
2
3
4
5
6
7


In [ ]:
# prefer a for-loop when you know the number of iterations in advance
# prefer a while loop when you don't know the number of iterations in advance

In [30]:
# Exercise: Make a Poisson-like counter. repeat 100 times

# parameter lambda, positive number (10)
# 1) initialize a counter = 0, currval = 1
# 2) multiply currval by uniform-random number U[0,1]
# 3) count iterations until e^(-l)
# 4) return counter

In [21]:
import numpy as np

def poissonCounter(lam):

  # initialize
  counter,currval = 0,1
  target = np.exp(-lam)

  # run algorithm (using while vs if)
  while currval > target:
    currval *= np.random.rand()
    counter += 1
  
  # return result
  return counter


In [26]:
poissonCounter(10)

9

In [29]:
# Generates distribution of this counter
poissonRand = np.zeros(100)

for i in range(100):
  poissonRand[i] = poissonCounter(10)

poissonRand.astype(int)

array([11, 10,  9, 11,  9,  8, 20, 10, 10, 12, 13, 12, 10, 10, 10,  5, 14,
       11, 10,  8, 10, 17, 14,  7, 12, 11,  9, 12, 14,  8, 16, 11, 12,  9,
        7,  8,  9, 15,  6,  9, 10, 14, 11, 13, 11, 10, 11, 12,  8, 12,  7,
       11, 12,  8, 13, 11, 13,  9, 10, 11,  7, 11,  9, 16,  7, 10,  7, 13,
       11,  9,  7, 11,  4, 14, 13,  7, 12, 14, 10,  7,  9, 14, 12, 13,  6,
       16, 12, 12,  9,  8, 12, 12, 10, 14, 12,  7, 14, 19,  7, 12])

In [ ]:
# same functionality but harder to read
def poissonCounter(l):
  k,p,t = 0,1,np.exp(-l)
  while p>t:
    k += 1
    p *= np.random.rand()
  return k

# appeal of compactness, maybe intentional
# problems:
#  1. harder to read
#  2. harder to find bugs
#  3. harder to modify
# don't pay by character

# .
# .
# .

# VIDEO: Initializing variables

In [ ]:
# Consequences of not initializing variables
for i in range(10):
  r[i] = i**2

print(r)

In [83]:
import numpy as np

# Initialize variables using numpy
r = np.zeros(10) # return an array of ten 0s
# r = np.full(10,1) ##return an array of ten 1s

for i in range(10):
  r[i] = i**2

print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [85]:
#(uninitialize) remove variable from python memory buffer
del r

r

NameError: name 'r' is not defined

In [93]:
# initialize empty np array
r = np.array([])
for i in range(10):
  r = np.append(r,i**2) # Append elements in numpy: Out-of-place operation

print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [91]:
# Initialize multi-dimensional np array
r = np.zeros((4,5))
# Accessing multi-dimensional np array
r[2,4] = 1
r[3,4] = 1

print(r)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]


In [100]:
# Exercise: time all three methods! (append, np.append, initialize)
# Important for optimizing code
# import time
# time.perf_counter() < clock the ongoing time in seconds

import time

toc = [0]*3
N = 10000

tic = time.perf_counter()
r = []
for i in range(N):
  r.append(i**2)
    
toc[0] = (time.perf_counter() - tic)*1000

# Stamp the current time (start counting)
tic = time.perf_counter()
r = np.zeros(N)
for i in range(N):
  r[i] = i**2
toc[1] = (time.perf_counter() - tic)*1000

# Stamp the current time (start counting)
tic = time.perf_counter()
r = np.array([])
for i in range(N):
  r = np.append(r,i**2)
toc[2] = (time.perf_counter() - tic)*1000

label = ["list-append", "np-append", "np-initialize"]
book = dict(zip(label, toc))
print(book) # in ms

{'list-append': 2.0083299996258575, 'np-append': 5.526620999262377, 'np-initialize': 65.51546100035921}


# .
# .
# .

# VIDEO: Enumerate and zip

In [30]:
# enumerate
import numpy as np

somenumbers = np.linspace(-5,5,7)

for i in range(len(somenumbers)):
  print('Index ' + str(i) + ' has value ' + str(somenumbers[i]))

# Compact way to do the above
print()
for i,n in enumerate(somenumbers):
  print('Index ' + str(i) + ' has value ' + str(n))

Index 0 has value -5.0
Index 1 has value -3.333333333333333
Index 2 has value -1.6666666666666665
Index 3 has value 0.0
Index 4 has value 1.666666666666667
Index 5 has value 3.333333333333334
Index 6 has value 5.0

Index 0 has value -5.0
Index 1 has value -3.333333333333333
Index 2 has value -1.6666666666666665
Index 3 has value 0.0
Index 4 has value 1.666666666666667
Index 5 has value 3.333333333333334
Index 6 has value 5.0


In [32]:
# Algorithm to determine if each letter in the word is a vowel
text = 'Hello my name is Mike'

vowels = np.zeros(len(text))

for i,l in enumerate(text):
  if l in 'aeiou':
    vowels[i] = 1

vowels != 0

array([False,  True, False, False,  True, False, False, False, False,
       False,  True, False,  True, False,  True, False, False, False,
        True, False,  True])

In [33]:
somelist = [3,5,4,2,4]
otherlist = ['d','e','r','s','x']

for i in range(len(somelist)):
  print(otherlist[i] + ' ' + str(somelist[i]))

# Compact way to do the above
print()
for j,i in zip(somelist,otherlist):
  print(i,j)

d 3
e 5
r 4
s 2
x 4

d 3
e 5
r 4
s 2
x 4


In [34]:
# if lists have different length. The zip cuts off at the one with shortest length
listA = [1,2,3]
listB = [4,5,6,7]

for i,j in zip(listA, listB):
    print(i,j)

1 4
2 5
3 6


In [68]:
z = zip(somelist,otherlist)
z # z[0] says error: it is not subscriptable

In [67]:
# Convert zip iterator object to a list
print(z) # z gets consumed (empty) after running once
list(z)

[(3, 'd'), (5, 'e'), (4, 'r'), (2, 's'), (4, 'x')]

In [70]:
# Alternatively, u should store the variables
lz = list(z)
# Then access elements for this zipped list
print(lz[0][0])

IndexError: list index out of range

In [73]:
# Exercise: given these two lists, create a dictionary using zip
names = ['alpha','beta','gamma']
values = [10,20,40]

D = dict(zip(names,values))
print(D)
D['gamma']

{'alpha': 10, 'beta': 20, 'gamma': 40}


40

# .
# .
# .

# VIDEO: Continue

In [75]:
# continue: skip the current iteration
# Print odd numbers
for i in range(10):
  if i%2==0:
    continue
  
  print(i)

1
3
5
7
9


In [81]:
# Only print out the consonants
text = 'HellO, my name is MikE'

for i in text:
  if i.lower() in 'aeiou':
    continue
  print(i)

H
l
l
,
 
m
y
 
n
m
 
s
 
M
k


# .
# .
# .

# VIDEO: Single-line loops / List comprehension

In [114]:
# reminder of single-line if-else
import random

x = random.randint(1,10) # randint is inclusive upper bound
print('I prefer smaller numbers.') if x>5 \
    else print(f'I like big numbers: {x}')


I like big numbers: 3


In [122]:
# list comprehension puts the output of print(i**2) into the list
# Since print outputs None, the list will be filled with None      
# But this serves the purpose of a single-line for loop

# for i in range(10):
    # if i > 5: 
        # print(i**2)
[print(i**2) for i in range(10) if i > 5]

36
49
64
81


[None, None, None, None]

In [116]:
n = print('hi')
print(n)

hi
None


In [ ]:
# Exercise (maybe in separate video?)
# convert the following loops into single-line loops


In [125]:
# Loop through first word
text = ['Promising','Yves','that','home','on','Nobb']

for word in text:
  print(word[0])

print(' ')

[print(word[0]) for word in text]; # ; suppresses the notebook from outputing final line

P
Y
t
h
o
N
 
P
Y
t
h
o
N


In [ ]:
# convert range to list

newlist = ['']*10

for i in range(10):
  if i%2==1:
    newlist[i] = 'Odd'
  else:
    newlist[i] = i
    
newlist

In [ ]:
newlist = [ 'Odd' if i%2==1 else i for i in range(10) ] # (expression) for iterater in range
newlist

In [132]:
import numpy as np

# exercise 2: repeat using lists and single-line for loops
x1 = np.linspace(-3,3,11)
y1 = x1**2

x2 = [i/(5/3) for i in range(-5,6)]
y2 = [i**2 for i in x2]

print(x1)
print(y1)
print(' ')
print(x2)
print(y2)


[-3.  -2.4 -1.8 -1.2 -0.6  0.   0.6  1.2  1.8  2.4  3. ]
[9.   5.76 3.24 1.44 0.36 0.   0.36 1.44 3.24 5.76 9.  ]
 
[-3.0, -2.4, -1.7999999999999998, -1.2, -0.6, 0.0, 0.6, 1.2, 1.7999999999999998, 2.4, 3.0]
[9.0, 5.76, 3.2399999999999993, 1.44, 0.36, 0.0, 0.36, 1.44, 3.2399999999999993, 5.76, 9.0]


# .
# .
# .

# VIDEO: Broadcasting in numpy

In [37]:
import numpy as np
import copy 
X = np.array([[1,2,3],
              [2,3,4],
              [3,4,5],
              [4,5,6]   ])

w = np.array([10,20,30])

# goal: add w to each row of X
# Given X.shape returns (4,3)
# We know X.shape[0] returns 4, the number of rows
Y = copy.deepcopy(X)
for i in range(X.shape[0]):
  Y[i,:] = X[i,:] + w

print(Y)
print(' ')
print(X)

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]
 
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [47]:
# SHORTCUT: using broadcasting (row-wise)
# python expands the row vector [10, 20, 30] into a matrix with repeated rows
X = np.array([[1,2,3],
              [2,3,4],
              [3,4,5],
              [4,5,6]   ])
w = np.array([10,20,30])

Y = X+w

print(X), print(' ')
print(w), print(' ')
print(Y)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
 
[10 20 30]
 
[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]


In [48]:
# broadcasting (column-vector-wise)
v = np.array([-1,0,1,0],ndmin=2).T # same as [ [-1],[0],[1],[0] ]

print(X), print(' ')
print(v), print(' ')
print(X*v)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
 
[[-1]
 [ 0]
 [ 1]
 [ 0]]
 
[[-1 -2 -3]
 [ 0  0  0]
 [ 3  4  5]
 [ 0  0  0]]


In [55]:
# exercise: 
# 1) create an array of integers from 0 to 8 (v)
# 2) reshape to a 3x3 matrix (M)
# 3) repeat that matrix to 9x3 (C)
# 4) broadcast-multiply with initial vector (B)

# 1
v = np.arange(9)
print(v), print(' ')

# 2
M = np.reshape(v,(3,3))
print(M), print(' ')

# 3
C = np.tile(M,(3,1)) #repeat all rows 3 times, all columns once
print(C), print(' ')

# 4
B = C*np.reshape(v,(len(v),1)) # or reshape(v,(-1,1))
print(B)

[0 1 2 3 4 5 6 7 8]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [ 0  3  6]
 [12 16 20]
 [30 35 40]
 [ 0  6 12]
 [21 28 35]
 [48 56 64]]


# .
# .
# .

# VIDEO: Function error checking and handling

In [59]:
# create a function that will input two numbers and output their product
def funfun(x,y):
  if not isinstance(x,(int,float)):
    raise Exception('Input x must be a number.')
  if not isinstance(y,(int,float)):
    raise Exception('Input y must be a number.')
  z = x*y
  return z

funfun(4.0,3)

12.0

In [70]:
# exercise: get this to work:
# funfun('4',3)

def funfun(x,y):
  
  # check if x is not a number
  if not isinstance(x,(int,float)):

    # check if x can be converted to a number
    if isinstance(x,str) and x.isnumeric():
      x = float(x)
      print('Note: converted x to a float.')
    
    # otherwise give error message
    else:
      raise Exception('Input x must be a number.')

  # This doesn't check if x is a string number
  if not isinstance(y,(int,float)):
    raise Exception('Input y must be a number.')

  z = x*y
  return z

funfun('4',3)

Note: converted x to a float.


12.0

In [73]:
# now try/except
# python jumps into except block as soon as error triggers
def funfunfun(x,y):
  try:
    return x**y
  except:
    print("Couldn't complete the mission.")

funfunfun(3,'asdf')

Couldn't complete the mission.
