# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401
##### Modified from original code

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [3]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some matrix multiplications by the @ operator ...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 0.41  0.76 -1.42  2.1  -1.72]
 [ 1.68  2.56 -1.64  1.94 -1.23]
 [ 0.52  1.93  0.28  0.89  0.09]]
 
[[-0.58  0.37  3.09  1.44]
 [ 0.46  0.72 -3.12 -0.84]
 [-0.15  0.68  0.68  0.82]
 [ 1.94 -2.1  -5.62 -0.52]
 [ 0.18  1.42 -2.33 -0.39]
 [ 0.41 -2.48  1.33  0.59]
 [-1.83  4.42  1.82 -0.9 ]]


# Using pytorch

In [5]:
# create some random matrices
A  = torch.randn(3,4) 
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float ) #create tensor from numpy

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ') # note tensor * ndarray is doable
print(np.round( A@C2  ,2))

tensor([[-2.0900, -1.1800,  0.8300,  0.4800,  1.8300, -1.4900,  5.1900],
        [-1.4400, -1.2600,  0.1700, -0.9000, -1.7400, -0.0700,  1.1100],
        [ 1.5300,  1.0400,  0.0800,  0.5000, -1.0800,  0.5100, -3.0700]],
       dtype=torch.float64)
 
tensor([[-2.0900, -1.1800,  0.8300,  0.4800,  1.8300, -1.4900,  5.1900],
        [-1.4400, -1.2600,  0.1700, -0.9000, -1.7400, -0.0700,  1.1100],
        [ 1.5300,  1.0400,  0.0800,  0.5000, -1.0800,  0.5100, -3.0700]])
